In [6]:
import pandas as pd
df = pd.read_csv('Archivo Financiero Liztex B005.csv', delimiter=';', encoding='latin1' )

In [10]:
df.dtypes

Sociedad               object
Unidad de negocio      object
Segmento               object
Cuentas                object
Periodo                 int64
Año                     int64
Mes                    object
Cecos                  object
Cebes                  object
Cliente                object
Material              float64
Moneda                 object
Real Periodo           object
Descripción cuenta     object
Volumen               float64
UM                     object
Subcategoria           object
Moneda.1               object
Real Periodo.1         object
Unnamed: 19           float64
-1                    float64
dtype: object

In [15]:
import numpy as np
df['Cecos'] = df['Cecos'].replace(np.nan, '')

In [21]:
df = df.drop(columns=['Unnamed: 19','-1'])

In [40]:
df[:1782]

,Sociedad,Unidad de negocio,Segmento,Cuentas,Periodo,Año,Mes,Cecos,Cebes,Cliente,Material,Moneda,Real Periodo,Descripción cuenta,Volumen,UM,Subcategoria,Moneda.1,Real Periodo.1
0,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010170,HN-00000012,20013479.0,Lempiras,360,Ventas Locales,220.0,ft3,Oxígeno,Dolares,14.91
1,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010101,HN-00000038,20013495.0,Lempiras,700,Ventas Locales,145.0,ft3,Acetileno,Dolares,29
2,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010170,HN-00000053,20013479.0,Lempiras,2100,Ventas Locales,1040.0,ft3,Oxígeno,Dolares,86.99
3,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010170,HN-00000061,20013479.0,Lempiras,450,Ventas Locales,220.0,ft3,Oxígeno,Dolares,18.64
4,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010170,HN-00000070,20013479.0,Lempiras,600,Ventas Locales,300.0,ft3,Oxígeno,Dolares,24.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1777,B005,Gases,Honduras,5012010050,3,2020,marzo,B005010500,NaN,NaN,10001912.0,Lempiras,115650.82,Costo De Venta Otros Bienes,NaN,NaN,Carburo,Dolares,4790.84
1778,B005,Gases,Honduras,5012010062,3,2020,marzo,B005010500,NaN,NaN,20013455.0,Lempiras,10462.31,Costo de Ventas Liquidos,NaN,NaN,Helio,Dolares,433.4
1779,B005,Gases,Honduras,5012010062,3,2020,marzo,B005010500,NaN,NaN,20013450.0,Lempiras,0,Costo de Ventas Liquidos,NaN,NaN,Aire comprimido,Dolares,0
1780,B005,Gases,Honduras,5012010062,3,2020,marzo,B005010500,NaN,NaN,20013479.0,Lempiras,7612.82,Costo de Ventas Liquidos,NaN,NaN,Oxígeno,Dolares,315.36
1781,B005,Gases,Honduras,5012010062,3,2020,marzo,B005010500,NaN,NaN,20013479.0,Lempiras,NaN,Costo de Ventas Liquidos,NaN,NaN,Oxígeno,Dolares,0

In [46]:
df['Cecos'].value_counts()

              5975
B005010100     747
B005010200     441
B005010500     330
B005010711      21
B005010170      14
B005010101       7
B005010105       7
B005010165       7
B005010109       7
B005010138       6
B005010163       3
B005010508       3
B005010139       1
Name: Cecos, dtype: int64

In [43]:
df[df['Real Periodo.1'].str.match('^-?[0-9]+.?[0-9]{0,2}') == False]

,Sociedad,Unidad de negocio,Segmento,Cuentas,Periodo,Año,Mes,Cecos,Cebes,Cliente,Material,Moneda,Real Periodo,Descripción cuenta,Volumen,UM,Subcategoria,Moneda.1,Real Periodo.1
6082,B005,Gases,Honduras,4011010001,3,2021,marzo,,B005010170,HN-00000663,20013479.0,Lempiras,600,Ventas Locales,300.0,Ft3,Oxígeno,Dolares,Q24.97
6083,B005,Gases,Honduras,4011010001,3,2021,marzo,,B005010101,HN-00000676,20013495.0,Lempiras,920,Ventas Locales,145.0,Ft3,Acetileno,Dolares,Q38.29
6084,B005,Gases,Honduras,4011010001,3,2021,marzo,,B005010170,HN-00000676,20013479.0,Lempiras,"1,600.00",Ventas Locales,220.0,Ft3,Oxígeno,Dolares,Q66.59
6085,B005,Gases,Honduras,4011010001,3,2021,marzo,,B005010170,HN-00000692,20013479.0,Lempiras,900,Ventas Locales,440.0,Ft3,Oxígeno,Dolares,Q37.45
6086,B005,Gases,Honduras,4011010001,3,2021,marzo,,B005010170,HN-00000712,20013479.0,Lempiras,900,Ventas Locales,440.0,Ft3,Oxígeno,Dolares,Q37.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6631,B005,Gases,Honduras,4011010001,6,2021,junio,,B005010170,HN-00000964,20013479.0,Lempiras,"9,000.00",Ventas Locales,5500.0,Ft3,Oxígeno,Dolares,Q375.22
6632,B005,Gases,Honduras,4011010001,6,2021,junio,,B005010105,HN-00000973,20013476.0,Lempiras,"1,500.00",Ventas Locales,220.0,Ft3,Argón,Dolares,Q62.54
6633,B005,Gases,Honduras,4011010001,6,2021,junio,,B005010170,HN-00000976,20013479.0,Lempiras,"17,400.00",Ventas Locales,8700.0,Ft3,Oxígeno,Dolares,Q725.42
6634,B005,Gases,Honduras,4011010001,6,2021,junio,,B005010105,HN-00000981,20013476.0,Lempiras,"3,000.00",Ventas Locales,440.0,Ft3,Argón,Dolares,Q125.07
6635,B005,Gases,Honduras,4011010001,6,2021,junio,,B005010101,HN-00000985,20013495.0,Lempiras,"1,800.00",Ventas Locales,290.0,Ft3,Acetileno,Dolares,Q75.04

In [22]:
df.head()

,Sociedad,Unidad de negocio,Segmento,Cuentas,Periodo,Año,Mes,Cecos,Cebes,Cliente,Material,Moneda,Real Periodo,Descripción cuenta,Volumen,UM,Subcategoria,Moneda.1,Real Periodo.1
0,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010170,HN-00000012,20013479.0,Lempiras,360,Ventas Locales,220.0,ft3,Oxígeno,Dolares,14.91
1,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010101,HN-00000038,20013495.0,Lempiras,700,Ventas Locales,145.0,ft3,Acetileno,Dolares,29
2,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010170,HN-00000053,20013479.0,Lempiras,2100,Ventas Locales,1040.0,ft3,Oxígeno,Dolares,86.99
3,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010170,HN-00000061,20013479.0,Lempiras,450,Ventas Locales,220.0,ft3,Oxígeno,Dolares,18.64
4,B005,Gases,Honduras,4011010001,1,2020,enero,,B005010170,HN-00000070,20013479.0,Lempiras,600,Ventas Locales,300.0,ft3,Oxígeno,Dolares,24.86